name = "beach_fortran"
version = "0.1.0"
license = "MIT"
author = "beach contributors"
maintainer = "beach contributors"
copyright = "2026"

[build]
auto-executables = true
auto-tests = false
auto-examples = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name = "beach_demo"
source-dir = "app"
main = "main.f90"

[[test]]
name = "test_app_config_parser"
source-dir = "test"
main = "test_app_config_parser.f90"

[[test]]
name = "test_boundary"
source-dir = "test"
main = "test_boundary.f90"

[[test]]
name = "test_restart"
source-dir = "test"
main = "test_restart.f90"
