name = "bemtracer_fortran"
version = "0.1.0"
license = "MIT"
author = "bemtracer contributors"
maintainer = "bemtracer contributors"
copyright = "2026"

[build]
auto-executables = true
auto-tests = false
auto-examples = false

[fortran]
implicit-typing = false
implicit-external = false
source-form = "free"

[[executable]]
name = "bemtracer_demo"
source-dir = "app"
main = "main.f90"
