program test_periodic2_operator_cache_mpi
  use bem_kinds, only: dp, i32
  use bem_mpi, only: mpi_context, mpi_initialize, mpi_shutdown, mpi_is_root, &
                     mpi_allreduce_sum_i32_scalar, mpi_allreduce_min_real_dp_array, &
                     mpi_allreduce_max_real_dp_array, mpi_world_barrier
  use bem_coulomb_fmm_core, only: fmm_options_type, fmm_plan_type, build_plan, destroy_plan
  use test_support, only: test_init, test_begin, test_end, test_summary, assert_true, assert_equal_i32
  implicit none

  type(mpi_context) :: mpi
  type(fmm_options_type) :: options
  type(fmm_plan_type) :: probe_plan, cold_plan, warm_plan
  real(dp) :: src_pos(3, 4), operator_bounds(2), operator_min(1), operator_max(1)
  integer(i32) :: global_build_count, global_cache_hits
  character(len=512) :: cache_path

  call mpi_initialize(mpi)
  call configure_fixture(src_pos, options)

  ! Discover the deterministic path, then remove any cache left by an interrupted run.
  call build_plan(probe_plan, src_pos, options)
  cache_path = probe_plan%periodic_cache_path
  call destroy_plan(probe_plan)
  if (mpi_is_root(mpi)) call delete_cache(cache_path)
  call mpi_world_barrier(mpi)

  call test_init(2)
  call test_begin('mpi_root_only_cold_build')
  call build_plan(cold_plan, src_pos, options)
  global_build_count = cold_plan%periodic_operator_build_count
  call mpi_allreduce_sum_i32_scalar(mpi, global_build_count)
  call assert_equal_i32(global_build_count, 1_i32, 'cached operator must be generated by one rank')
  call assert_true(cold_plan%periodic_root_operator_ready, 'broadcast cached operator must be ready')
  call assert_true(len_trim(cold_plan%periodic_cache_fingerprint) > 0, 'fingerprint must be present on every rank')
  operator_min(1) = sum(abs(cold_plan%periodic_root_operator))
  operator_max = operator_min
  call mpi_allreduce_min_real_dp_array(mpi, operator_min)
  call mpi_allreduce_max_real_dp_array(mpi, operator_max)
  operator_bounds = [operator_min(1), operator_max(1)]
  call assert_true(abs(operator_bounds(2) - operator_bounds(1)) <= 1.0e-13_dp*max(1.0_dp, operator_bounds(2)), &
                   'broadcast operator differs across ranks')
  call test_end()

  call test_begin('mpi_all_rank_warm_hit')
  call build_plan(warm_plan, src_pos, options)
  global_build_count = warm_plan%periodic_operator_build_count
  call mpi_allreduce_sum_i32_scalar(mpi, global_build_count)
  global_cache_hits = merge(1_i32, 0_i32, warm_plan%periodic_cache_hit)
  call mpi_allreduce_sum_i32_scalar(mpi, global_cache_hits)
  call assert_equal_i32(global_build_count, 0_i32, 'warm cache must not regenerate the operator')
  call assert_equal_i32(global_cache_hits, mpi%size, 'warm cache hit must be reported on every rank')
  call assert_true(trim(warm_plan%periodic_cache_path) == trim(cold_plan%periodic_cache_path), &
                   'cache path differs across cold and warm builds')
  call test_end()

  call destroy_plan(cold_plan)
  call destroy_plan(warm_plan)
  if (mpi_is_root(mpi)) call delete_cache(cache_path)
  call mpi_world_barrier(mpi)
  call test_summary()
  call mpi_shutdown(mpi)

contains

  subroutine configure_fixture(positions, config)
    real(dp), intent(out) :: positions(3, 4)
    type(fmm_options_type), intent(out) :: config

    positions(:, 1) = [0.15_dp, 0.20_dp, -0.10_dp]
    positions(:, 2) = [0.75_dp, 0.25_dp, 0.08_dp]
    positions(:, 3) = [0.30_dp, 0.80_dp, 0.12_dp]
    positions(:, 4) = [0.82_dp, 0.72_dp, -0.06_dp]
    config%theta = 0.45_dp
    config%leaf_max = 2_i32
    config%order = 2_i32
    config%use_periodic2 = .true.
    config%periodic_axes = [1_i32, 2_i32]
    config%periodic_len = [1.0_dp, 1.0_dp]
    config%periodic_image_layers = 1_i32
    config%periodic_far_correction = 'cached_kneq0'
    config%periodic_ewald_layers = 2_i32
    config%periodic_cache_dir = '.'
    config%periodic_generation_tolerance = 1.0e-8_dp
    config%target_box_min = [0.0_dp, 0.0_dp, -0.5_dp]
    config%target_box_max = [1.0_dp, 1.0_dp, 0.5_dp]
  end subroutine configure_fixture

  subroutine delete_cache(path)
    character(len=*), intent(in) :: path
    call delete_file(path)
    call delete_file(trim(path)//'.lock')
  end subroutine delete_cache

  subroutine delete_file(path)
    character(len=*), intent(in) :: path
    logical :: exists
    integer :: unit
    inquire (file=trim(path), exist=exists)
    if (.not. exists) return
    open (newunit=unit, file=trim(path), status='old')
    close (unit, status='delete')
  end subroutine delete_file

end program test_periodic2_operator_cache_mpi
