! Generated by tools/generate_config_layout.py; edit beach/config/_layout.py.
module bem_config_layout_paths
  implicit none
  private
  public :: legacy_layout_path, grouped_layout_table
contains
  !> Return the existing reader path for one grouped setting.
  function legacy_layout_path(path) result(legacy)
    character(len=*), intent(in) :: path
    character(len=:), allocatable :: legacy
    select case (path)
    case ('particles.tracking.dt_s')
      legacy = 'sim.dt'
    case ('particles.tracking.max_steps_per_particle')
      legacy = 'sim.max_step'
    case ('run.rng_seed')
      legacy = 'sim.rng_seed'
    case ('run.batch_count')
      legacy = 'sim.batch_count'
    case ('run.batch.duration_s')
      legacy = 'sim.batch_duration'
    case ('run.batch.duration_steps')
      legacy = 'sim.batch_duration_step'
    case ('output.diagnostics.charge_rel_change_threshold')
      legacy = 'sim.tol_rel'
    case ('output.diagnostics.charge_floor_c')
      legacy = 'sim.q_floor'
    case ('fields.solver.method')
      legacy = 'sim.field_solver'
    case ('fields.solver.normalization')
      legacy = 'sim.field_normalization'
    case ('fields.solver.length_scale_m')
      legacy = 'sim.field_length_scale'
    case ('fields.solver.tree.theta')
      legacy = 'sim.tree_theta'
    case ('fields.solver.tree.leaf_max')
      legacy = 'sim.tree_leaf_max'
    case ('fields.solver.auto_fmm_min_elements')
      legacy = 'sim.tree_min_nelem'
    case ('fields.periodic.image_layers')
      legacy = 'sim.field_periodic_image_layers'
    case ('fields.periodic.backend')
      legacy = 'sim.field_periodic_far_correction'
    case ('fields.periodic.ewald_alpha')
      legacy = 'sim.field_periodic_ewald_alpha'
    case ('fields.periodic.ewald_layers')
      legacy = 'sim.field_periodic_ewald_layers'
    case ('fields.periodic.cache_dir')
      legacy = 'sim.field_periodic_cache_dir'
    case ('fields.periodic.generation_tolerance')
      legacy = 'sim.field_periodic_generation_tolerance'
    case ('fields.external.electric_v_m')
      legacy = 'sim.e0'
    case ('fields.external.electric_magnitude_v_m')
      legacy = 'sim.e0_abs'
    case ('fields.external.electric_azimuth_deg')
      legacy = 'sim.e0_phi_xy_deg'
    case ('fields.external.electric_elevation_deg')
      legacy = 'sim.e0_phi_z_deg'
    case ('fields.external.magnetic_t')
      legacy = 'sim.b0'
    case ('particles.tracking.events.policy')
      legacy = 'sim.multiple_box_events_policy'
    case ('particles.tracking.events.retry_backend')
      legacy = 'sim.multiple_box_events_retry_backend'
    case ('particles.tracking.events.discard_count_grace')
      legacy = 'sim.multiple_box_events_soft_discard_count_grace'
    case ('particles.tracking.events.discard_fraction_limit')
      legacy = 'sim.multiple_box_events_soft_discard_fraction_limit'
    case ('particles.tracking.events.discard_charge_warning_c')
      legacy = 'sim.multiple_box_events_soft_discard_abs_charge_limit'
    case ('particles.raycast.max_bounces')
      legacy = 'sim.raycast_max_bounce'
    case ('fields.periodic.lower_boundary_model')
      legacy = 'periodic2.lower_boundary_model'
    case ('fields.periodic.reference.mode_layers')
      legacy = 'periodic2.reference_mode_layers'
    case ('fields.periodic.reference.panel_quadrature_order')
      legacy = 'periodic2.panel_quadrature_order'
    case ('run.batch.adaptive.max_nonzero_mode_potential_step_v')
      legacy = 'periodic2.max_nonzero_mode_potential_step'
    case ('sheath.closure')
      legacy = 'surface_current_model.model'
    case ('sheath.response')
      legacy = 'surface_current_model.response_backend'
    case ('sheath.zhao.branch')
      legacy = 'surface_current_model.zhao_branch'
    case ('sheath.zhao.root_selection')
      legacy = 'surface_current_model.zhao_root_selection'
    case ('sheath.species.electron')
      legacy = 'surface_current_model.electron_species'
    case ('sheath.species.ion')
      legacy = 'surface_current_model.ion_species'
    case ('sheath.species.photoelectron')
      legacy = 'surface_current_model.photoelectron_species'
    case ('sheath.stationary.solar_elevation_deg')
      legacy = 'surface_current_model.solar_elevation_deg'
    case ('sheath.stationary.photoelectron_ref_density_m3')
      legacy = 'surface_current_model.photoelectron_ref_density_m3'
    case ('sheath.stationary.photoelectron_source_scale')
      legacy = 'surface_current_model.photoelectron_source_scale'
    case ('sheath.stationary.reference_area_m2')
      legacy = 'surface_current_model.reference_area_m2'
    case ('sheath.stationary.outflow_refresh_batches')
      legacy = 'surface_current_model.outflow_refresh_batches'
    case ('sheath.table.path')
      legacy = 'surface_current_model.response_table_path'
    case ('sheath.coupling.mean_field_update')
      legacy = 'surface_current_model.implicit_zero_mode'
    case ('sheath.coupling.rtol')
      legacy = 'surface_current_model.coupling_rtol'
    case ('sheath.coupling.max_iterations')
      legacy = 'surface_current_model.coupling_max_iterations'
    case ('sheath.coupling.relaxation')
      legacy = 'surface_current_model.coupling_relaxation'
    case ('sheath.photoelectrons.closure')
      legacy = 'surface_current_model.photoelectron_closure'
    case ('sheath.photoelectrons.spectrum_bins_per_decade')
      legacy = 'surface_current_model.photoelectron_spectrum_bins_per_decade'
    case ('output.enabled')
      legacy = 'output.write_files'
    case ('output.dir')
      legacy = 'output.dir'
    case ('output.final.mesh_potential')
      legacy = 'output.write_mesh_potential'
    case ('output.history.potential')
      legacy = 'output.write_potential_history'
    case ('output.history.stride_batches')
      legacy = 'output.history_stride'
    case ('output.checkpoint.stride_batches')
      legacy = 'output.checkpoint_stride'
    case ('run.restart.from')
      legacy = 'output.restart_from'
    case ('fields.boundary')
      legacy = 'field_boundary.mode'
    case ('particles.boundary.x_low')
      legacy = 'particle_boundary.x_low'
    case ('particles.boundary.x_high')
      legacy = 'particle_boundary.x_high'
    case ('particles.boundary.y_low')
      legacy = 'particle_boundary.y_low'
    case ('particles.boundary.y_high')
      legacy = 'particle_boundary.y_high'
    case ('particles.boundary.z_low')
      legacy = 'particle_boundary.z_low'
    case ('particles.boundary.z_high')
      legacy = 'particle_boundary.z_high'
    case ('particles.boundary.open_model')
      legacy = 'particle_boundary.ordinary_open_model'
    case ('particles.reservoir.inflow_model')
      legacy = 'reservoir.inflow_model'
    case ('particles.reservoir.phi_infty_v')
      legacy = 'reservoir.phi_infty'
    case ('particles.reservoir.face_potential_grid_n')
      legacy = 'reservoir.face_potential_grid_n'
    case ('mesh.obj.path')
      legacy = 'mesh.obj_path'
    case ('mesh.obj.scale')
      legacy = 'mesh.obj_scale'
    case ('mesh.obj.rotation')
      legacy = 'mesh.obj_rotation'
    case ('mesh.obj.offset')
      legacy = 'mesh.obj_offset'
    case ('mesh.obj.surface_model')
      legacy = 'mesh.surface_model'
    case ('mesh.obj.surface_side')
      legacy = 'mesh.surface_side'
    case ('domain')
      legacy = 'domain'
    case ('mesh.mode')
      legacy = 'mesh.mode'
    case ('mesh.groups')
      legacy = 'mesh.groups'
    case ('mesh.templates')
      legacy = 'mesh.templates'
    case ('particles.species.species_key')
      legacy = 'particles.species.species_key'
    case ('particles.species.enabled')
      legacy = 'particles.species.enabled'
    case ('particles.species.charge_c')
      legacy = 'particles.species.q_particle'
    case ('particles.species.mass_kg')
      legacy = 'particles.species.m_particle'
    case ('particles.species.distribution.model')
      legacy = 'particles.species.velocity_distribution'
    case ('particles.species.distribution.number_density_cm3')
      legacy = 'particles.species.number_density_cm3'
    case ('particles.species.distribution.number_density_m3')
      legacy = 'particles.species.number_density_m3'
    case ('particles.species.distribution.temperature_ev')
      legacy = 'particles.species.temperature_ev'
    case ('particles.species.distribution.temperature_k')
      legacy = 'particles.species.temperature_k'
    case ('particles.species.distribution.drift_velocity_m_s')
      legacy = 'particles.species.drift_velocity'
    case ('particles.species.distribution.grid_path')
      legacy = 'particles.species.velocity_grid_path'
    case ('particles.species.distribution.grid_pdf_kind')
      legacy = 'particles.species.velocity_grid_pdf_kind'
    case ('particles.species.distribution.particle_flux_m2_s')
      legacy = 'particles.species.particle_flux_m2_s'
    case ('particles.species.distribution.current_density_a_m2')
      legacy = 'particles.species.current_density_a_m2'
    case ('particles.species.source.mode')
      legacy = 'particles.species.source_mode'
    case ('particles.species.source.pos_low')
      legacy = 'particles.species.pos_low'
    case ('particles.species.source.pos_high')
      legacy = 'particles.species.pos_high'
    case ('particles.species.source.normal')
      legacy = 'particles.species.source_normal'
    case ('particles.species.source.inject_face')
      legacy = 'particles.species.inject_face'
    case ('particles.species.source.ray_direction')
      legacy = 'particles.species.ray_direction'
    case ('particles.species.source.region_mode')
      legacy = 'particles.species.inject_region_mode'
    case ('particles.species.source.uv_low')
      legacy = 'particles.species.uv_low'
    case ('particles.species.source.uv_high')
      legacy = 'particles.species.uv_high'
    case ('particles.species.source.emit_current_density_a_m2')
      legacy = 'particles.species.emit_current_density_a_m2'
    case ('particles.species.source.deposit_opposite_charge_on_emit')
      legacy = 'particles.species.deposit_opposite_charge_on_emit'
    case ('particles.species.source.normal_drift_speed_m_s')
      legacy = 'particles.species.normal_drift_speed'
    case ('particles.species.sampling.volume_macro_particles_per_batch')
      legacy = 'particles.species.npcls_per_step'
    case ('particles.species.sampling.weight')
      legacy = 'particles.species.w_particle'
    case ('particles.species.sampling.target_macro_particles_per_batch')
      legacy = 'particles.species.target_macro_particles_per_batch'
    case ('particles.species.sampling.rays_per_batch')
      legacy = 'particles.species.rays_per_batch'
    case ('particles.species.sampling.velocity_grid_sampling')
      legacy = 'particles.species.velocity_grid_sampling'
    case ('particles.species.charging.closure')
      legacy = 'particles.species.surface_charge_closure'
    case ('particles.species.charging.target_absorbed_current_a')
      legacy = 'particles.species.target_absorbed_current_a'
    case ('particles.species.charging.target_emission_current_a')
      legacy = 'particles.species.target_emission_current_a'
    case ('particles.species.boundary')
      legacy = 'particles.species.boundary'
    case ('particles.species.inflow')
      legacy = 'particles.species.boundary_inflow'
    case default
      legacy = ''
    end select
  end function legacy_layout_path

  !> Recognize structural tables, rejecting unknown empty groups.
  logical function grouped_layout_table(path) result(known)
    character(len=*), intent(in) :: path
    select case (path)
    case ('')
      known = .true.
    case ('fields')
      known = .true.
    case ('fields.external')
      known = .true.
    case ('fields.periodic')
      known = .true.
    case ('fields.periodic.reference')
      known = .true.
    case ('fields.solver')
      known = .true.
    case ('fields.solver.tree')
      known = .true.
    case ('mesh')
      known = .true.
    case ('mesh.obj')
      known = .true.
    case ('output')
      known = .true.
    case ('output.checkpoint')
      known = .true.
    case ('output.diagnostics')
      known = .true.
    case ('output.final')
      known = .true.
    case ('output.history')
      known = .true.
    case ('particles')
      known = .true.
    case ('particles.boundary')
      known = .true.
    case ('particles.raycast')
      known = .true.
    case ('particles.reservoir')
      known = .true.
    case ('particles.species')
      known = .true.
    case ('particles.species.charging')
      known = .true.
    case ('particles.species.distribution')
      known = .true.
    case ('particles.species.sampling')
      known = .true.
    case ('particles.species.source')
      known = .true.
    case ('particles.tracking')
      known = .true.
    case ('particles.tracking.events')
      known = .true.
    case ('run')
      known = .true.
    case ('run.batch')
      known = .true.
    case ('run.batch.adaptive')
      known = .true.
    case ('run.restart')
      known = .true.
    case ('sheath')
      known = .true.
    case ('sheath.coupling')
      known = .true.
    case ('sheath.coupling.atol')
      known = .true.
    case ('sheath.photoelectrons')
      known = .true.
    case ('sheath.species')
      known = .true.
    case ('sheath.stationary')
      known = .true.
    case ('sheath.table')
      known = .true.
    case ('sheath.zhao')
      known = .true.
    case default
      known = .false.
    end select
  end function grouped_layout_table
end module bem_config_layout_paths
