#!/bin/bash
# Generated by tools/periodic_object_validation.py. Placeholder values are
# resolved during `stage`; this template does not submit work by itself.
#SBATCH -p @PARTITION@
#SBATCH -t @WALLTIME@
#SBATCH --rsc p=6:t=112:c=112
#SBATCH -J @JOB_NAME@
#SBATCH -o @LOG_DIR@/%x.%j.out
#SBATCH -e @LOG_DIR@/%x.%j.err

set -euo pipefail

if [ -f /usr/share/Modules/init/bash ]; then
  . /usr/share/Modules/init/bash
fi
current_sys="$(module -t list 2>&1 | grep -E '^Sys(A|B|C|CL|G)/' | head -n 1 || true)"
if [ -n "${current_sys}" ] && [ "${current_sys}" != "SysA/2022" ]; then
  module switch "${current_sys}" SysA/2022
elif [ -z "${current_sys}" ]; then
  module load SysA/2022
fi
modules="$(module -t list 2>&1)"
grep -q '^SysA/2022$' <<<"${modules}" || {
  printf '%s\n' 'SysA/2022 module is required on gr20001a.' >&2
  exit 2
}
if grep -Eq '^Sys(B|C|CL|G)/' <<<"${modules}"; then
  printf '%s\n' 'A non-SysA system module remains loaded.' >&2
  exit 2
fi
module load intel/2023.2 intelmpi/2023.2

export OMP_NUM_THREADS=112
export OMP_PROC_BIND=spread
export OMP_PLACES=cores
export PYTHONPATH="@REPO_ROOT@${PYTHONPATH:+:${PYTHONPATH}}"
export PYTHONDONTWRITEBYTECODE=1

VALIDATION_ROOT="@VALIDATION_ROOT@"
BINARY="@BINARY@"
BINARY_SHA256="@BINARY_SHA256@"
TOOL="@TOOL@"
JOB_NAME="@JOB_NAME@"
SOURCE_COMMIT="@SOURCE_COMMIT@"
SOURCE_ROOT="@REPO_ROOT@"
SOURCE_HASH_FILE="@SOURCE_HASH_FILE@"
SOURCE_HASH_SHA256="@SOURCE_HASH_SHA256@"
JOB_TOKEN="${SLURM_JOB_ID:-manual}.${JOB_NAME}"
STARTED_AT="$(date -Iseconds)"
STATUS_DIR="${VALIDATION_ROOT}/provenance/jobs"
HASH_LOG="${VALIDATION_ROOT}/provenance/hashes/${JOB_TOKEN}.sha256"
MODULE_LOG="${VALIDATION_ROOT}/provenance/modules/${JOB_TOKEN}.txt"

record_status() {
  local exit_code=$?
  local temporary="${STATUS_DIR}/${JOB_TOKEN}.status.tmp"
  {
    printf 'job_id=%s\n' "${SLURM_JOB_ID:-manual}"
    printf 'job_name=%s\n' "${JOB_NAME}"
    printf 'source_commit=%s\n' "${SOURCE_COMMIT}"
    printf 'resources=p=6:t=112:c=112\n'
    printf 'started_at=%s\n' "${STARTED_AT}"
    printf 'ended_at=%s\n' "$(date -Iseconds)"
    printf 'exit_code=%s\n' "${exit_code}"
  } > "${temporary}"
  mv "${temporary}" "${STATUS_DIR}/${JOB_TOKEN}.status"
}
trap record_status EXIT

mkdir -p "@LOG_DIR@" "${VALIDATION_ROOT}/provenance/time" \
  "${STATUS_DIR}" "${VALIDATION_ROOT}/provenance/hashes" \
  "${VALIDATION_ROOT}/provenance/modules"
module list 2>&1 | tee "${MODULE_LOG}"
printf '%s  %s\n' "${BINARY_SHA256}" "${BINARY}" | \
  sha256sum --check - | tee "${HASH_LOG}"
printf '%s  %s\n' "${SOURCE_HASH_SHA256}" "${SOURCE_HASH_FILE}" | \
  sha256sum --check - | tee -a "${HASH_LOG}"
(
  cd "${SOURCE_ROOT}"
  sha256sum --check "${SOURCE_HASH_FILE}"
) | tee -a "${HASH_LOG}"

@COMMANDS@
